URl: ""
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Ed martin's portfolio forcybersecurity projects]
description: [this page is a overview of the projects I have been working on and other acheivements ]

theme: jekyll-theme-hacker
