URl: ""
remote_theme: pages-theme/hacker@v0.2.0
Plugins:
-jekyll-remote -theme

title: [Ed martin's portfolio forcybersecurity projects]
description: [this page is a overview of the projects I have been working on and other acheivements ]
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
